// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/aviatrix/aviatirx_controller.proto

package aviatrix

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AviatrixControllerservice_GetAviatrixControllers_FullMethodName = "/aviatrix.AviatrixControllerservice/GetAviatrixControllers"
)

// AviatrixControllerserviceClient is the client API for AviatrixControllerservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the service
type AviatrixControllerserviceClient interface {
	// Define an RPC method to fetch aviatrixcontroller data
	GetAviatrixControllers(ctx context.Context, in *GetAviatrixControllersRequest, opts ...grpc.CallOption) (*GetAviatrixControllersResponse, error)
}

type aviatrixControllerserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewAviatrixControllerserviceClient(cc grpc.ClientConnInterface) AviatrixControllerserviceClient {
	return &aviatrixControllerserviceClient{cc}
}

func (c *aviatrixControllerserviceClient) GetAviatrixControllers(ctx context.Context, in *GetAviatrixControllersRequest, opts ...grpc.CallOption) (*GetAviatrixControllersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAviatrixControllersResponse)
	err := c.cc.Invoke(ctx, AviatrixControllerservice_GetAviatrixControllers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AviatrixControllerserviceServer is the server API for AviatrixControllerservice service.
// All implementations must embed UnimplementedAviatrixControllerserviceServer
// for forward compatibility.
//
// Define the service
type AviatrixControllerserviceServer interface {
	// Define an RPC method to fetch aviatrixcontroller data
	GetAviatrixControllers(context.Context, *GetAviatrixControllersRequest) (*GetAviatrixControllersResponse, error)
	mustEmbedUnimplementedAviatrixControllerserviceServer()
}

// UnimplementedAviatrixControllerserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAviatrixControllerserviceServer struct{}

func (UnimplementedAviatrixControllerserviceServer) GetAviatrixControllers(context.Context, *GetAviatrixControllersRequest) (*GetAviatrixControllersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAviatrixControllers not implemented")
}
func (UnimplementedAviatrixControllerserviceServer) mustEmbedUnimplementedAviatrixControllerserviceServer() {
}
func (UnimplementedAviatrixControllerserviceServer) testEmbeddedByValue() {}

// UnsafeAviatrixControllerserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AviatrixControllerserviceServer will
// result in compilation errors.
type UnsafeAviatrixControllerserviceServer interface {
	mustEmbedUnimplementedAviatrixControllerserviceServer()
}

func RegisterAviatrixControllerserviceServer(s grpc.ServiceRegistrar, srv AviatrixControllerserviceServer) {
	// If the following call pancis, it indicates UnimplementedAviatrixControllerserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AviatrixControllerservice_ServiceDesc, srv)
}

func _AviatrixControllerservice_GetAviatrixControllers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAviatrixControllersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviatrixControllerserviceServer).GetAviatrixControllers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AviatrixControllerservice_GetAviatrixControllers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviatrixControllerserviceServer).GetAviatrixControllers(ctx, req.(*GetAviatrixControllersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AviatrixControllerservice_ServiceDesc is the grpc.ServiceDesc for AviatrixControllerservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AviatrixControllerservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aviatrix.AviatrixControllerservice",
	HandlerType: (*AviatrixControllerserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAviatrixControllers",
			Handler:    _AviatrixControllerservice_GetAviatrixControllers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aviatrix/aviatirx_controller.proto",
}
